/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package problema.carteiro.chines;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public Grafo GrafoEuleriano(){
        Grafo grafoEuleriano = new Grafo();

        grafoEuleriano.addVertice(1);

        return grafoEuleriano;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Grafo grafo1 = new Grafo();

        //adciona os vértices
        grafo1.addVertice(1);
        grafo1.addVertice(2);
        grafo1.addVertice(3);
        grafo1.addVertice(4);
        grafo1.addVertice(5);
        grafo1.addVertice(6);
        grafo1.addVertice(7);

        //adiciona as arestas
        grafo1.addAresta(1, 2);
        grafo1.addAresta(1, 4);
        grafo1.addAresta(1, 7);
        grafo1.addAresta(2, 5);
        grafo1.addAresta(2, 6);
        grafo1.addAresta(2, 3);
        grafo1.addAresta(3, 4);
        grafo1.addAresta(5, 6);

        for (Vertice ver : grafo1.getListaAdjacencia().keySet()) {
            System.out.print(ver.n + ": ");
            for (Vertice adjver: grafo1.getListaAdjacencia().get(ver)) {
                System.out.print(adjver.n + " ");
            }
            System.out.println();
        }

    }
}
